PruebaAcidLabs/Models/Artista.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PruebaAcidLabs.Models
{
    public class Artista
    {
        public string ID { get; set; }
        public string NombreArtista { get; set; }
        public string PopularidadArtista { get; set; }

        public virtual ICollection<Album> Albumes { get; set; }
    }
}

PruebaAcidLabs/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PruebaAcidLabs.DAL;
using PruebaAcidLabs.Models;

namespace PruebaAcidLabs.Controllers
{
    public class AlbumController : Controller
    {
        private SpotifyContext db = new SpotifyContext();

        // GET: Album
        public ActionResult Index(string id)
        {
            //var albumes = db.Albumes.Include(a => a.Artista);
            //return View(albumes.ToList());

            var query = from p in db.Albumes
                        where p.ArtistaID == id
                        orderby p.Año descending
                        select p;
            return View(query.Include(a => a.Artista).ToList());
        }

        // GET: Album/Details/5
        public ActionResult Details(string id)
        {
            var query = from p in db.Pistas 
                        where p.AlbumID == id
                        group p by p.AlbumID into g
                        select new
                        {
                            g.Key,
                            Popularidad = g.Average(p => p.Popularidad)
                        };
            
            var query2 = from p in db.Pistas
                        where p.AlbumID == id
                        group p by p.NombrePista into g
                        select new
                        {
                            g.Key,
                            LongitudPista = g.Max(p => p.Duracion)
                        };

            ViewBag.PopularidadPromedio = query.FirstOrDefault().Popularidad;
            ViewBag.PistaMasLarga = query2.FirstOrDefault().Key;
            ViewBag.LongitudPistaMasLarga = query2.FirstOrDefault().LongitudPista;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albumes.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        // GET: Album/Create
        public ActionResult Create()
        {
            ViewBag.ArtistaID = new SelectList(db.Artistas, "ID", "NombreArtista");
            return View();
        }

        // POST: Album/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ArtistaID,NombreAlbum,Año,Disponibilidad")] Album album)
        {
            if (ModelState.IsValid)
            {
                db.Albumes.Add(album);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ArtistaID = new SelectList(db.Artistas, "ID", "NombreArtista", album.ArtistaID);
            return View(album);
        }

        // GET: Album/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albumes.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            ViewBag.ArtistaID = new SelectList(db.Artistas, "ID", "NombreArtista", album.ArtistaID);
            return View(album);
        }

        // POST: Album/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ArtistaID,NombreAlbum,Año,Disponibilidad")] Album album)
        {
            if (ModelState.IsValid)
            {
                db.Entry(album).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ArtistaID = new SelectList(db.Artistas, "ID", "NombreArtista", album.ArtistaID);
            return View(album);
        }

        // GET: Album/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albumes.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        // POST: Album/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Album album = db.Albumes.Find(id);
            db.Albumes.Remove(album);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PruebaAcidLabs/Controllers/ArtistaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PruebaAcidLabs.DAL;
using PruebaAcidLabs.Models;

namespace PruebaAcidLabs.Controllers
{
    public class ArtistaController : Controller
    {
        private SpotifyContext db = new SpotifyContext();

        // GET: Artista
        public ActionResult Index()
        {
            return View(db.Artistas.ToList());
        }

        // GET: Artista/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artista artista = db.Artistas.Find(id);
            if (artista == null)
            {
                return HttpNotFound();
            }
            return View(artista);
        }

        // GET: Artista/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Artista/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,NombreArtista,PopularidadArtista")] Artista artista)
        {
            if (ModelState.IsValid)
            {
                db.Artistas.Add(artista);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(artista);
        }

        // GET: Artista/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artista artista = db.Artistas.Find(id);
            if (artista == null)
            {
                return HttpNotFound();
            }
            return View(artista);
        }

        // POST: Artista/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,NombreArtista,PopularidadArtista")] Artista artista)
        {
            if (ModelState.IsValid)
            {
                db.Entry(artista).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(artista);
        }

        // GET: Artista/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artista artista = db.Artistas.Find(id);
            if (artista == null)
            {
                return HttpNotFound();
            }
            return View(artista);
        }

        // POST: Artista/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Artista artista = db.Artistas.Find(id);
            db.Artistas.Remove(artista);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PruebaAcidLabs/Views/Artista/Create.cshtml
@model PruebaAcidLabs.Models.Artista

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Artista</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NombreArtista, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreArtista, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreArtista, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PopularidadArtista, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PopularidadArtista, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PopularidadArtista, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PruebaAcidLabs/Views/Artista/Delete.cshtml
@model PruebaAcidLabs.Models.Artista

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Artista</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NombreArtista)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreArtista)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PopularidadArtista)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PopularidadArtista)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PruebaAcidLabs/Views/Artista/Details.cshtml
@model PruebaAcidLabs.Models.Artista

@{
    ViewBag.Title = "Details";
}

<h2>Detalles</h2>

<div>
    <h4>Artista</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NombreArtista)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreArtista)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PopularidadArtista)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PopularidadArtista)
        </dd>

        <dt>
            Albumes
        </dt>

        <dd>
            @Html.ActionLink("Lista de Albumes", "Index", "Album", new { id = Model.ID }, null)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PruebaAcidLabs/Views/Artista/Edit.cshtml
@model PruebaAcidLabs.Models.Artista

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Artista</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.NombreArtista, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreArtista, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreArtista, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PopularidadArtista, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PopularidadArtista, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PopularidadArtista, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PruebaAcidLabs/Views/Artista/Index.cshtml
@model IEnumerable<PruebaAcidLabs.Models.Artista>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NombreArtista)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PopularidadArtista)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NombreArtista)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PopularidadArtista)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>