PruebaAcidLabs/Models/Album.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace PruebaAcidLabs.Models
{
    public class Album
    {
        public string ID { get; set; }
        public string ArtistaID { get; set; }
        public string NombreAlbum { get; set; }
        public int Año { get; set; }
        public string Disponibilidad { get; set; }

        public virtual Artista Artista { get; set; }
        public virtual ICollection<Pista> Pistas { get; set; }
    }
}

PruebaAcidLabs/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PruebaAcidLabs.DAL;
using PruebaAcidLabs.Models;

namespace PruebaAcidLabs.Controllers
{
    public class AlbumController : Controller
    {
        private SpotifyContext db = new SpotifyContext();

        // GET: Album
        public ActionResult Index(string id)
        {
            //var albumes = db.Albumes.Include(a => a.Artista);
            //return View(albumes.ToList());

            var query = from p in db.Albumes
                        where p.ArtistaID == id
                        orderby p.Año descending
                        select p;
            return View(query.Include(a => a.Artista).ToList());
        }

        // GET: Album/Details/5
        public ActionResult Details(string id)
        {
            var query = from p in db.Pistas 
                        where p.AlbumID == id
                        group p by p.AlbumID into g
                        select new
                        {
                            g.Key,
                            Popularidad = g.Average(p => p.Popularidad)
                        };
            
            var query2 = from p in db.Pistas
                        where p.AlbumID == id
                        group p by p.NombrePista into g
                        select new
                        {
                            g.Key,
                            LongitudPista = g.Max(p => p.Duracion)
                        };

            ViewBag.PopularidadPromedio = query.FirstOrDefault().Popularidad;
            ViewBag.PistaMasLarga = query2.FirstOrDefault().Key;
            ViewBag.LongitudPistaMasLarga = query2.FirstOrDefault().LongitudPista;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albumes.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        // GET: Album/Create
        public ActionResult Create()
        {
            ViewBag.ArtistaID = new SelectList(db.Artistas, "ID", "NombreArtista");
            return View();
        }

        // POST: Album/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ArtistaID,NombreAlbum,Año,Disponibilidad")] Album album)
        {
            if (ModelState.IsValid)
            {
                db.Albumes.Add(album);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ArtistaID = new SelectList(db.Artistas, "ID", "NombreArtista", album.ArtistaID);
            return View(album);
        }

        // GET: Album/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albumes.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            ViewBag.ArtistaID = new SelectList(db.Artistas, "ID", "NombreArtista", album.ArtistaID);
            return View(album);
        }

        // POST: Album/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ArtistaID,NombreAlbum,Año,Disponibilidad")] Album album)
        {
            if (ModelState.IsValid)
            {
                db.Entry(album).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ArtistaID = new SelectList(db.Artistas, "ID", "NombreArtista", album.ArtistaID);
            return View(album);
        }

        // GET: Album/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albumes.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        // POST: Album/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Album album = db.Albumes.Find(id);
            db.Albumes.Remove(album);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PruebaAcidLabs/Controllers/PistaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PruebaAcidLabs.DAL;
using PruebaAcidLabs.Models;

namespace PruebaAcidLabs.Controllers
{
    public class PistaController : Controller
    {
        private SpotifyContext db = new SpotifyContext();

        // GET: Pista
        public ActionResult Index(string id)
        {
            //return View(db.Pistas.ToList());

            var query = from p in db.Pistas
                        where p.AlbumID == id
                        orderby p.NumeroPista ascending
                        select p;
            return View(query.Include(a => a.Album).ToList());
        }

        // GET: Pista/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pista pista = db.Pistas.Find(id);
            if (pista == null)
            {
                return HttpNotFound();
            }
            return View(pista);
        }

        // GET: Pista/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pista/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,AlbumID,NombrePista,NumeroPista,Duracion,Popularidad")] Pista pista)
        {
            if (ModelState.IsValid)
            {
                db.Pistas.Add(pista);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pista);
        }

        // GET: Pista/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pista pista = db.Pistas.Find(id);
            if (pista == null)
            {
                return HttpNotFound();
            }
            return View(pista);
        }

        // POST: Pista/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,AlbumID,NombrePista,NumeroPista,Duracion,Popularidad")] Pista pista)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pista).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pista);
        }

        // GET: Pista/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pista pista = db.Pistas.Find(id);
            if (pista == null)
            {
                return HttpNotFound();
            }
            return View(pista);
        }

        // POST: Pista/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Pista pista = db.Pistas.Find(id);
            db.Pistas.Remove(pista);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PruebaAcidLabs/Views/Album/Create.cshtml
@model PruebaAcidLabs.Models.Album

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Album</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArtistaID, "ArtistaID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ArtistaID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ArtistaID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NombreAlbum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreAlbum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreAlbum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Año, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Año, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Año, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Disponibilidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Disponibilidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Disponibilidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PruebaAcidLabs/Views/Album/Delete.cshtml
@model PruebaAcidLabs.Models.Album

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Album</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Artista.NombreArtista)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Artista.NombreArtista)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NombreAlbum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreAlbum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Año)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Año)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Disponibilidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Disponibilidad)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PruebaAcidLabs/Views/Album/Details.cshtml
@model PruebaAcidLabs.Models.Album

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Album</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Artista.NombreArtista)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Artista.NombreArtista)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NombreAlbum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreAlbum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Año)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Año)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Disponibilidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Disponibilidad)
        </dd>

        <dt>
            Popularidad Promedio
        </dt> 
        
        <dd>
            @ViewBag.PopularidadPromedio
        </dd>

        <dt>
            Pista Mas Larga
        </dt> 
        
        <dd>
            @ViewBag.PistaMasLarga
        </dd>

        <dt>
            Longitud
        </dt> 
        
        <dd>
            @ViewBag.LongitudPistaMasLarga
        </dd>

        <dt>
            Pistas
        </dt>

        <dd>
            @Html.ActionLink("Lista de Pistas", "Index", "Pista", new { id = Model.ID }, null)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PruebaAcidLabs/Views/Album/Edit.cshtml
@model PruebaAcidLabs.Models.Album

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Album</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.ArtistaID, "ArtistaID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ArtistaID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ArtistaID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NombreAlbum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreAlbum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreAlbum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Año, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Año, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Año, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Disponibilidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Disponibilidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Disponibilidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PruebaAcidLabs/Views/Album/Index.cshtml
@model IEnumerable<PruebaAcidLabs.Models.Album>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Artista.NombreArtista)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NombreAlbum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Año)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Disponibilidad)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Artista.NombreArtista)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NombreAlbum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Año)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Disponibilidad)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>